### ISSUE TITLE
Run CI on a nightly schedule

### ISSUE THREAD

**Issue by mferrera** [equinor/fmu-config#57]
```yml
  schedule:
    # Run nightly to check that tests are working with latest dependencies
    - cron: "0 0 * * *"
 ```
