### ISSUE TITLE
Add dotfile to root of revision as standard

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-config#58]
Based on discussions 15. nov 2023

Currently, some masterdata are stored in `global_variables.yml`. These are technically metadata _about the model_, and contain mostly identifiers to entities in SMDA, including `country`, `field`, `discovery`, `coordinate_reference_system` and `stratigraphic_column`. These elements do not change frequently, and may not natively belong in `global_variables.yml`.

When pushing data to Sumo, it is also required that the model metadata contains a reference to the _asset_ which in turn is mapped to the term _asset_ in Sumo - used for access control, storage choices, etc. This is also currently included in `global_variables.yml`.

There is a need for more consistent storage of configuration of static nature. This proposal is to move such elements out of `global_variables.yml` to another more suitable location.

Proposal:
On the root of (each) FMU revision, we place a dotfile called `.fmu`. The contents of this file can be expanded as needed, but a first iteration content can be:

```yaml
masterdata:
  smda:
    country:
      - identifier: Norway
        uuid: ad214d85-8a1d-19da-e053-c918a4889309
    discovery:
      - short_identifier: DROGON
        uuid: ad214d85-8a1d-19da-e053-c918a4889309
    field:
      - identifier: DROGON
        uuid: 00000000-0000-0000-0000-000000000000
    coordinate_system:
      identifier: ST_WGS84_UTM37N_P32637
      uuid: ad214d85-dac7-19da-e053-c918a4889309
    stratigraphic_column:
      identifier: DROGON_HAS_NO_STRATCOLUMN
      uuid: 00000000-0000-0000-0000-000000000000
access:
  asset: MyAsset
  sumo:
    enabled: true
```

Current _masterdata.yml: https://github.com/equinor/fmu-drogon/blob/master/fmuconfig/input/_masterdata.yml

__Detection of `global_variables.yml`__
A frequent problem is that local installations place `global_variables.yml` in non-standard place and/or with no-standard names. The `.fmu` could be a no-discussions location to refer to the location of the `global_variables.yml`. This would, as one example, be relevant for [this issue](https://github.com/equinor/fmu-dataio/issues/393) in fmu-dataio.

__Detection of Sumo__
During development of Sumo, there may be a need to programmatically find out if a particular model revision belongs to an asset onboarded on Sumo. This may replace the use of the `--sumo` optional argument in FMU data, which is also relevant for [this issue](https://github.com/equinor/fmu-dataio/issues/393) in fmu-dataio.

__file format__
User should ideally "never" access the dotfile (hence it is a dotfile/hidden file). We start with using YAML format for this file, but without guarantees that this may change in the future. Related to this, it is probably smart to have some dedicated tooling on top of this configuration item, so that clients can e.g.

```python
from fmu.config import StaticConfig # names to be discussed
static = StaticConfig()
print(static)
>>> 
```
