### ISSUE TITLE
Issue with preserving dictionary order

### ISSUE THREAD

**Issue by tnatt** [equinor/fmu-config#74]
A user have reported that the dictionary order is no longer preserved when reading the gloabl_variables file, it comes in alphabetical order instead. This happened with the latest komodo release that introduced the `fmu-config==1.2.1`

This is very likely related to this PR wher oyaml was removed https://github.com/equinor/fmu-config/commit/97a58094a034be14daf750d3e896cf7fa6a5441c

We should investigate if this is the case and fix it.

**Example:**
in global_config.yml:
```yaml

global:
  EQUIL_INFO: 
    REGION_SOUTH: 
      EQUIL: 1
      GOC: 2300
      OWC: 2500 

    REGION_NORTH: 
      EQUIL: 2
      GOC: 3000
      OWC: 3400
```
in global_variables.yml (order is different) :
```yaml

global:
  EQUIL_INFO:
    REGION_NORTH: 
      EQUIL: 2
      GOC: 3000
      OWC: 3400
    REGION_SOUTH: 
      EQUIL: 1
      GOC: 2300
      OWC: 2500 



```
