### ISSUE TITLE
YAML to IPL lists issues

### ISSUE THREAD

**Issue by jcrivenaes** [equinor/fmu-config#9]
To see if the use of explicitly defined dtype was solving the issue I encountered another one. I had to manually write the variables names, if not I had the mistake below and the variables were not considered and a list is used instead.
```
  PARAM_PER_ZONE_DTYPE:
    dtype: float
    values:
      - 10 ~ <PARAM_PER_ZONE_DTYPE_0>
      - -10 ~ <PARAM_PER_ZONE_DTYPE_1>         
      - 2.58  ~ <PARAM_PER_ZONE_DTYPE_2>        
      - 3.48 ~ <PARAM_PER_ZONE_DTYPE_3>     
!# Your template key contains lowercase letter: <values_0>
!# Your template key contains lowercase letter: <values_0>

```
